"""
config_model.py
---------------
This module defines the ConfigModel class, which acts as a central data model for holding
the current camera configuration dictionary in a PyQt6 GUI application using the Picamera2 library.

ConfigModel wraps a configuration dictionary (as generated by Picamera2's create_preview_configuration,
create_still_configuration, or create_video_configuration) and emits a signal when the configuration changes.
This enables robust two-way data binding with the GUI.

Typical usage:
    config_model = ConfigModel()
    config_model.set_config(picam2.create_preview_configuration())
    config_model.configChanged.connect(some_slot)
"""

from PyQt6.QtCore import QObject, pyqtSignal
from picamera2 import Picamera2

class ConfigModel(QObject):
    configChanged = pyqtSignal(dict)

    def __init__(self, initial_config=None):
        super().__init__()
        if initial_config is not None:
            self._config = initial_config
        else:
            cam = Picamera2()
            self._config = cam.create_preview_configuration()

    @property
    def config(self):
        """Get the current configuration dictionary."""
        return self._config

    def set_config(self, config_dict):
        """Set the configuration dictionary and emit configChanged if changed."""
        if config_dict != self._config:
            self._config = config_dict
            self.configChanged.emit(self._config)

    def update_config(self, key, value):
        """Update a single key in the configuration and emit configChanged."""
        if self._config.get(key) != value:
            self._config[key] = value
            self.configChanged.emit(self._config)

    def get_nested(self, section, key):
        """Get a value from a nested section, e.g., get_nested('main', 'size')."""
        return self._config.get(section, {}).get(key)

    def set_nested(self, section, key, value):
        """Set a value in a nested section and emit configChanged if changed."""
        if section in self._config and self._config[section].get(key) != value:
            self._config[section][key] = value
            self.configChanged.emit(self._config)

    def to_dict(self):
        """Return the current configuration as a dictionary."""
        return dict(self._config)

# Create a singleton instance for use throughout the app
config_model = ConfigModel()

if __name__ == "__main__":
    # Simple test of ConfigModel with Picamera2
    from PyQt6.QtWidgets import QApplication
    import sys
    import pprint

    app = QApplication(sys.argv)
    picam2 = Picamera2()

    # Create initial config using Picamera2's preview configuration
    preview_config = picam2.create_preview_configuration()
    model = ConfigModel(preview_config)

    pp = pprint.PrettyPrinter(indent=2)

    def on_config_changed(cfg):
        print("Config changed:")
        pp.pprint(cfg)

    model.configChanged.connect(on_config_changed)

    print("Initial config:")
    pp.pprint(model.config)

    # Test get/set for nested keys: 'main', 'format', 'size', 'preserve_ar'
    print("\nTesting nested get/set for 'main', 'format', 'size', and 'preserve_ar':")
    print("Original main.format:", model.get_nested('main', 'format'))
    print("Original main.size:", model.get_nested('main', 'size'))
    print("Original main.preserve_ar:", model.get_nested('main', 'preserve_ar'))

    model.set_nested('main', 'format', 'YUV420')
    model.set_nested('main', 'size', (1280, 720))
    model.set_nested('main', 'preserve_ar', False)

    print("Updated main.format:", model.get_nested('main', 'format'))
    print("Updated main.size:", model.get_nested('main', 'size'))
    print("Updated main.preserve_ar:", model.get_nested('main', 'preserve_ar'))